# Generated by Django 5.2 on 2025-05-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
