# Generated by Django 5.2 on 2025-05-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_review_tour_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='child',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
