# Generated by Django 5.2 on 2025-04-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, choices=[('Asia', 'Osiyo'), ('Europe', 'Yevropa'), ('Africa', 'Afrika'), ('South America', 'Janubiy Amerika'), ('North America', 'Shimoliy Amerika')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='continent',
            field=models.CharField(blank=True, choices=[('Asia', 'Osiyo'), ('Europe', 'Yevropa'), ('Africa', 'Afrika'), ('South America', 'Janubiy Amerika'), ('North America', 'Shimoliy Amerika')], max_length=20, null=True),
        ),
    ]
