# Generated by Django 5.2 on 2025-04-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_country_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='persons',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
