# Generated by Django 5.2 on 2025-04-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_country_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
