# Generated by Django 5.2 on 2025-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_country_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='continent',
            field=models.CharField(blank=True, choices=[('Asia', 'Osiyo'), ('Europe', 'Yevropa'), ('Africa', 'Afrika'), ('South America', 'Janubiy Amerika'), ('North America', 'Shimoliy Amerika')], max_length=20, null=True),
        ),
    ]
