# Generated by Django 5.2 on 2025-04-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_category_country_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cities',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
