# Generated by Django 5.2 on 2025-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_country_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
