# Generated by Django 5.2 on 2025-04-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_country_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ManyToManyField(blank=True, to='tour.category'),
        ),
    ]
