# Generated by Django 5.2 on 2025-04-20 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_tour_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='countries',
        ),
        migrations.AddField(
            model_name='tour',
            name='countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.country'),
        ),
    ]
