# Generated by Django 5.2 on 2025-04-20 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_remove_tour_countries_tour_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='destinations',
        ),
        migrations.AddField(
            model_name='tour',
            name='destinations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.destination'),
        ),
    ]
